if(DEFINED ZEPHYR_BASE)
    zephyr_library_named(lifecycle)
    zephyr_library_sources(src/LifecycleManager.cpp)
    zephyr_library_include_directories(include)
    zephyr_include_directories(include)
else()
    add_library(lifecycle STATIC src/LifecycleManager.cpp)
    target_include_directories(lifecycle PUBLIC include)
    target_compile_features(lifecycle PUBLIC cxx_std_17)
endif()
