apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
metadata:
  name: nucleo-board 
  namespace: default
endpoint: grpc.jumpstarter.example.com:443
token: "<token>"
export:
  flasher:
    type: jumpstarter_driver_probe_rs.driver.ProbeRs
    config:
      probe_rs_path: "/opt/homebrew/bin/probe-rs"
      chip: "STM32H755ZI"
      protocol: "swd"
  console:
    type: jumpstarter_driver_pyserial.driver.PySerial
    config:
      url: "/dev/cu.usbmodem1203"
      baudrate: 115200
  someip:
    type: jumpstarter_driver_someip.driver.SomeIp
    config:
      host: "192.168.100.1"
      port: 30490
      transport_mode: UDP
      remote_host: "192.168.100.10"
      remote_port: 30490