if(ZEPHYR_BASE)
    zephyr_library_named(lighting)
    zephyr_library_sources(src/LightingController.cpp)
    zephyr_library_link_libraries(ports)
    target_include_directories(lighting PUBLIC include)
else()
    add_library(lighting STATIC src/LightingController.cpp)
    target_include_directories(lighting PUBLIC include)
    target_link_libraries(lighting PUBLIC ports someip_ids)
endif()

if(BUILD_TESTS)
    add_subdirectory(tests)
endif()
