if(ZEPHYR_BASE)
    zephyr_library_named(speed_simulator)
    zephyr_library_sources(src/SpeedSimulator.cpp)
    zephyr_library_link_libraries(ports)
    target_include_directories(speed_simulator PUBLIC include)
else()
    add_library(speed_simulator STATIC src/SpeedSimulator.cpp)
    target_include_directories(speed_simulator PUBLIC include)
    target_link_libraries(speed_simulator PUBLIC ports someip_ids)
endif()

if(BUILD_TESTS)
    add_subdirectory(tests)
endif()
