/********************************************************************************
 * Copyright (c) 2024 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License 2.0 which is available at
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-License-Identifier: Apache-2.0
 ********************************************************************************/

// Vendored from eclipse-kuksa/kuksa-databroker tag 0.6.1
// Source: proto/kuksa/val/v2/val.proto

syntax = "proto3";

package kuksa.val.v2;

option go_package = "kuksa/val/v2";

import "kuksa/val/v2/types.proto";

service VAL {
  rpc GetValue(GetValueRequest) returns (GetValueResponse);
  rpc GetValues(GetValuesRequest) returns (GetValuesResponse);
  rpc Subscribe(SubscribeRequest) returns (stream SubscribeResponse);
  rpc Actuate(ActuateRequest) returns (ActuateResponse);
  rpc BatchActuate(BatchActuateRequest) returns (BatchActuateResponse);
  rpc ListMetadata(ListMetadataRequest) returns (ListMetadataResponse);
  rpc PublishValue(PublishValueRequest) returns (PublishValueResponse);
  rpc OpenProviderStream(stream OpenProviderStreamRequest) returns (stream OpenProviderStreamResponse);
  rpc GetServerInfo(GetServerInfoRequest) returns (GetServerInfoResponse);
}

message GetValueRequest {
  SignalID signal_id = 1;
}
message GetValueResponse {
  Datapoint data_point = 1;
}

message GetValuesRequest {
  repeated SignalID signal_ids = 1;
}
message GetValuesResponse {
  repeated Datapoint data_points = 1;
}

message SubscribeRequest {
  repeated string signal_paths = 1;
  uint32 buffer_size = 2;
  Filter filter = 3;
}
message SubscribeResponse {
  map<string, Datapoint> entries = 1;
}

message ActuateRequest {
  SignalID signal_id = 1;
  Value value = 2;
}
message ActuateResponse {}

message BatchActuateRequest {
  repeated ActuateRequest actuate_requests = 1;
}
message BatchActuateResponse {}

message ListMetadataRequest {
  string root = 1;
  string filter = 2;
}
message ListMetadataResponse {
  repeated Metadata metadata = 1;
}

message PublishValueRequest {
  SignalID signal_id = 1;
  Datapoint data_point = 2;
}
message PublishValueResponse {}

message PublishValuesRequest {
  uint32 request_id = 1;
  map<int32, Datapoint> data_points = 2;
}
message PublishValuesResponse {
  uint32 request_id = 1;
  map<int32, Error> status = 2;
}

message ProvideActuationRequest {
  repeated SignalID actuator_identifiers = 1;
}
message ProvideActuationResponse {}

message BatchActuateStreamRequest {
  repeated ActuateRequest actuate_requests = 1;
}
message BatchActuateStreamResponse {
  SignalID signal_id = 1;
  Error error = 2;
}

message OpenProviderStreamRequest {
  oneof action {
    ProvideActuationRequest provide_actuation_request = 1;
    PublishValuesRequest publish_values_request = 2;
    BatchActuateStreamResponse batch_actuate_stream_response = 3;
  }
}
message OpenProviderStreamResponse {
  oneof action {
    ProvideActuationResponse provide_actuation_response = 1;
    PublishValuesResponse publish_values_response = 2;
    BatchActuateStreamRequest batch_actuate_stream_request = 3;
  }
}

message GetServerInfoRequest {}
message GetServerInfoResponse {
  string name = 1;
  string version = 2;
  string commit_hash = 3;
}
