if(ZEPHYR_BASE)
    zephyr_library_named(ignition)
    zephyr_library_sources(src/IgnitionController.cpp)
    zephyr_library_link_libraries(ports vehicle_mode)
    target_include_directories(ignition PUBLIC include)
else()
    add_library(ignition STATIC src/IgnitionController.cpp)
    target_include_directories(ignition PUBLIC include)
    target_link_libraries(ignition PUBLIC ports vehicle_mode)
endif()

if(BUILD_TESTS)
    add_subdirectory(tests)
endif()
