if(ZEPHYR_BASE)
    zephyr_library_named(cloud_gateway_client)
    zephyr_library_sources(src/CloudGatewayClient.cpp)
    zephyr_library_link_libraries(ports)
    target_include_directories(cloud_gateway_client PUBLIC include)
else()
    add_library(cloud_gateway_client STATIC src/CloudGatewayClient.cpp)
    target_include_directories(cloud_gateway_client PUBLIC include)
    target_link_libraries(cloud_gateway_client PUBLIC ports)
endif()

if(BUILD_TESTS)
    add_subdirectory(tests)
endif()
