FROM fedora:42

RUN dnf install -y --setopt=install_weak_deps=False \
        rpm-build rpmdevtools \
        createrepo_c \
        cmake gcc-c++ git-core \
        systemd-rpm-macros systemd-devel \
        grpc-devel grpc-plugins \
        protobuf-devel protobuf-compiler \
        openssl-devel \
    && dnf clean all

RUN rpmdev-setuptree

WORKDIR /src
ENTRYPOINT ["/bin/bash"]
