FROM fedora:41

RUN dnf install -y --setopt=install_weak_deps=False \
        rpm-build rpmdevtools \
        cmake gcc-c++ git-core \
        systemd-rpm-macros \
    && dnf clean all

RUN rpmdev-setuptree

WORKDIR /src
ENTRYPOINT ["/bin/bash"]
