if(ZEPHYR_BASE)
    zephyr_library_named(door_lock)
    zephyr_library_sources(src/DoorLockController.cpp)
    zephyr_library_link_libraries(ports)
    target_include_directories(door_lock PUBLIC include)
else()
    add_library(door_lock STATIC src/DoorLockController.cpp)
    target_include_directories(door_lock PUBLIC include)
    target_link_libraries(door_lock PUBLIC ports)
endif()

if(BUILD_TESTS)
    add_subdirectory(tests)
endif()
